[server]
maxUploadSize = 10
headless = true
runOnSave = true

[browser]
gatherUsageStats = false

[theme]
base = "light"
primaryColor = "#246953"
backgroundColor = "#FAFBF8"
secondaryBackgroundColor = "#EFF3EC"
textColor = "#20362E"
font = "sans serif"
